[package]
name        = "disassembler"
version     = "0.1.0"
edition     = "2024"
author      = "Chuck Norris"
description = "A simple disassembler for EN.695.744"

[dependencies]
serde = { version = "1.0.219", features = [ "derive" ] }
